### ISSUE TITLE
Language?

### ISSUE THREAD

**Issue by GraysonHuey** [GraysonHuey/BeFake#1]
What language do you think we should write this app in?

**Comment by Ne0Byt3** [comment]
maybe kotlin for the android version idk about the ios version

**Comment by GraysonHuey** [comment]
Well then I'm gonna have to learn a new language

**Comment by KeysDeveloper** [comment]
Actually I was thinking Java mostly bc it is known more for Android and I can do it. Idk what to do about IOS I think we have to learn Swift and get a Mac

**Comment by GraysonHuey** [comment]
I was thinking Java, but I’m fine with whatever we do. I’ll still have to learn a new language either way lol

**Comment by KeysDeveloper** [comment]
I actually have been wanting to learn Swift so maybe I can do that as well but if you want to learn either you are welcome too

**Comment by GraysonHuey** [comment]
I think at least one of us is gonna have to learn Swift
Isn’t Apple really strict about what language is used in apps?

**Comment by KeysDeveloper** [comment]
Yea they are really strict. They say I think we should use either Obj. C or Swift but Swift is newer

**Comment by KeysDeveloper** [comment]
Yea but we still need a mac or something else

**Comment by GraysonHuey** [comment]
I mean, Eric has a Mac so maybe he could help out

**Comment by KeysDeveloper** [comment]
OHHHHH ERIC HAS A MAC

**Comment by KeysDeveloper** [comment]
GET ERIC RIGHT NOW!!!

**Comment by GraysonHuey** [comment]
Hunter went over to Eric’s the other day lol

**Comment by KeysDeveloper** [comment]
lol

**Comment by Ne0Byt3** [comment]
Ok so we are gonna do java for the android version and swift (xcode) for the iOS version. Eric does have a mac but he wants us to be at his house to use it so we still need one. 
I want to learn swift but that's just me

**Comment by GraysonHuey** [comment]
Sounds like a plan
Java for Android and Swift for iOS
