### ISSUE TITLE
Tools?

### ISSUE THREAD

**Issue by GraysonHuey** [GraysonHuey/BeFake#2]
What photoshop tools should we include in the app?

**Comment by Ne0Byt3** [comment]
I was thinking liquify for sure, idk what else we would include

**Comment by GraysonHuey** [comment]
Yeah, we definitely need liquify
I feel like we need more tools than that though... it might be hard to match a prompt with just liquify

We're gonna need feedback from other team members to get an idea of what to do

**Comment by KeysDeveloper** [comment]
Personally, I think that we should scrap the idea of adding editing tools in general bc 1. They have their phones. 2. Regular gallery apps have editing software included

**Comment by GraysonHuey** [comment]
So are you saying that they should upload an edited picture of themselves? If that is what you are saying, I don't think it'll work because they could just upload a screenshot of the prompt and automatically win...

**Comment by Ne0Byt3** [comment]
Yeah

**Comment by KeysDeveloper** [comment]
Bad idea bc we literally cannot do it there is no way to find the place that they implemented the prompt so we cant do that.

**Comment by KeysDeveloper** [comment]
I think we can still do my idea bc according to the article I'm reading for Java rn we can detect if a human face is in the image and according to that information we can continue

**Comment by GraysonHuey** [comment]
Maybe we could have a few basic tools available to everyone and then have a fairly cheap in-app purchase that unlocks the rest of them

**Comment by GraysonHuey** [comment]
It could be called VIP or something and I could make a badge for it

**Comment by GraysonHuey** [comment]
We could also let users watch **ONE** ad to temporarily unlock all of the tools (for like 3 days or something)

**Comment by Ne0Byt3** [comment]
Ok so instead of the algorithm, a person on the discord said we should just use a voting system. Yeah people could vote dishonestly but they could restrict voting to only friends kinda like how you can post publicly on bereal. I think the Xp and levels would come from streaks instead of your votes

**Comment by GraysonHuey** [comment]
Hmm
That's actually a pretty good idea

**Comment by Ne0Byt3** [comment]
So the default could be on friends only (like bereal) then there could be an option when you post to make it public (like bereal) but the voting would be public as well

**Comment by GraysonHuey** [comment]
I like that better than creating an AI to rate it

**Comment by GraysonHuey** [comment]
I'm gonna close this issue bc its kinda irrelevant now lol
if you guys have any ideas, just put them in the discussions tab
